services:
  stripper:
    build:
      dockerfile: ./Dockerfile.podcast-stripper
      context: .
    image: stripper
    container_name: stripper
    command: [ "python", "stripper.py", "/var/podcasts", "--monitor" ]
    restart: "no"
    # Contains OPEN_AI_KEY
    env_file:
      - podcast-stripper/secrets.env
    volumes:
      - podcasts:/var/podcasts
  manager:
    build:
      dockerfile: ./Dockerfile.podcast-manager
      context: .
    image: manager
    container_name: manager
    command: [ "python", "manage-feeds.py", "/var/podcasts" ]
    restart: "no"
    volumes:
      - podcasts:/var/podcasts
    environment:
      INTERVAL: '10'
      PODCAST_ROOT: 'https://rhew.org/podcasts'

volumes:
  podcasts:
