FROM python:3

WORKDIR /usr/src/app
ADD podcast-stripper/stripper.py .
ADD podcast-stripper/ffmpeg_util.py .
ADD podcast-stripper/openai_util.py .
ADD podcast-stripper/playlist.py .
ADD podcast-stripper/checkmark.png .
ADD common/file_util.py .
ADD podcast-stripper/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update
RUN apt-get install ffmpeg -y

RUN pip install pyasyncore
# Allow installation to fail when building locally
RUN pip install audioop-lts; exit 0

ENV PYTHONUNBUFFERED=1

COPY version .

CMD [ "python", "./stripper.py" ]

