FROM python:3

WORKDIR /usr/src/app
ADD podcast-manager/manage-feeds.py .
ADD podcast-manager/config.py .
ADD common/file_util.py .
ADD podcast-manager/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

CMD [ "python", "./manage-feeds.py" ]

